// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-MyJqN5dWUmoNHrHU-SH5beBDe8J5cs',
    appId: '1:582078325614:web:051596fad0c211e6f8977f',
    messagingSenderId: '582078325614',
    projectId: 'vendo-b822f',
    authDomain: 'vendo-b822f.firebaseapp.com',
    storageBucket: 'vendo-b822f.firebasestorage.app',
    measurementId: 'G-LV8PEFJZQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0u5sWJyaFMieuktoU8LLQ7mccNPmVsU',
    appId: '1:582078325614:android:39f073b6e5d68606f8977f',
    messagingSenderId: '582078325614',
    projectId: 'vendo-b822f',
    storageBucket: 'vendo-b822f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcM74QgceYhRz6QC7y5kQ40sClhmxw4s',
    appId: '1:582078325614:ios:2084923dce9f8b2ff8977f',
    messagingSenderId: '582078325614',
    projectId: 'vendo-b822f',
    storageBucket: 'vendo-b822f.firebasestorage.app',
    iosClientId: '582078325614-0fi1v0u07660kotjaefp3ggj72tvvans.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcM74QgceYhRz6QC7y5kQ40sClhmxw4s',
    appId: '1:582078325614:ios:2084923dce9f8b2ff8977f',
    messagingSenderId: '582078325614',
    projectId: 'vendo-b822f',
    storageBucket: 'vendo-b822f.firebasestorage.app',
    iosClientId: '582078325614-0fi1v0u07660kotjaefp3ggj72tvvans.apps.googleusercontent.com',
    iosBundleId: 'com.example.vendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-MyJqN5dWUmoNHrHU-SH5beBDe8J5cs',
    appId: '1:582078325614:web:f25b867740424cf6f8977f',
    messagingSenderId: '582078325614',
    projectId: 'vendo-b822f',
    authDomain: 'vendo-b822f.firebaseapp.com',
    storageBucket: 'vendo-b822f.firebasestorage.app',
    measurementId: 'G-G2JE2LRMLY',
  );
}
